library("aws.s3")
library("dplyr")
library("DT")
library("formattable")
library("ggrepel")
library("pdftools")
library("plotly")
library("RColorBrewer")
library("shiny")
library("shinyalert")
library("shinydashboard")
library("shinyjs")
library("shinymanager")
library("shinythemes")
library("shinyWidgets")
library("showtext")
library("xlsx")
font_add_google(name = "Nanum Gothic")
